clc; clear all; close all

% set boundary
% boundary = [-1,-1,-.01;  ...
%              1,-1,-.01;  ...
%              1, 1,-.01;  ...
%             -1, 1,-.01;  ...
%             -1,-1, .01;  ...
%              1,-1, .01;  ...
%              1, 1, .01;  ...
%             -1, 1, .01]; ...
%             
boundary = [-1, 0, -1/sqrt(2);...
             1, 0, -1/sqrt(2);...
             0,-1,  1/sqrt(2);...
             0, 1,  1/sqrt(2)]; ...

% initilize random points
n = 100;

pts = rand(n,3)*0.1 + repmat([0.5,0.5,0.5],100,1);
pts(:,1) = pts(:,1)*(max(boundary(:,1))-min(boundary(:,1))) + min(boundary(:,1));
pts(:,2) = pts(:,2)*(max(boundary(:,2))-min(boundary(:,2))) + min(boundary(:,2));
pts(:,3) = pts(:,3)*(max(boundary(:,3))-min(boundary(:,3))) + min(boundary(:,3));

[G,optPts,f,g] = optiVoronoi3D(pts,boundary);

%plotGrid(G)

save('unitSquare200')
    